services:
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
    volumes:
      - ./patient_data:/app/patient_data
    ports:
      - 8000:8000
      - 3000:3000
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DB_PORT=${DB_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
