# Generated by Django 5.0.3 on 2024-03-19 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=7,
                    ),
                ),
                ("birth_date", models.DateField()),
                ("deceased_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("A", "Annulled"),
                            ("D", "Divorced"),
                            ("I", "Interlocutory"),
                            ("L", "Legally Separated"),
                            ("M", "Married"),
                            ("C", "Common Law"),
                            ("P", "Polygamous"),
                            ("T", "Domestic partner"),
                            ("U", "unmarried"),
                            ("S", "Never Married"),
                            ("W", "Widowed"),
                            ("UNK", "unknown"),
                        ],
                        max_length=3,
                    ),
                ),
                ("language", models.CharField(max_length=20)),
            ],
        ),
    ]
