# Generated by Django 5.0.3 on 2024-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_data", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "gender__in",
                        {
                            "female": "Female",
                            "male": "Male",
                            "other": "Other",
                            "unknown": "Unknown",
                        },
                    )
                ),
                name="valid_gender_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "marital_status__in",
                        {
                            "A": "Annulled",
                            "C": "Common Law",
                            "D": "Divorced",
                            "I": "Interlocutory",
                            "L": "Legally Separated",
                            "M": "Married",
                            "P": "Polygamous",
                            "S": "Never Married",
                            "T": "Domestic partner",
                            "U": "unmarried",
                            "UNK": "unknown",
                            "W": "Widowed",
                        },
                    )
                ),
                name="valid_marital_status_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "language__in",
                        {
                            "ar": "Arabic",
                            "bg": "Bulgarian",
                            "bg-BG": "Bulgarian (Bulgaria)",
                            "bn": "Bengali",
                            "bs": "Bosnian",
                            "bs-BA": "Bosnian (Bosnia and Herzegovina)",
                            "cs": "Czech",
                            "cs-CZ": "Czech (Czechia)",
                            "da": "Danish",
                            "da-DK": "Danish (Denmark)",
                            "de": "German",
                            "de-AT": "German (Austria)",
                            "de-CH": "German (Switzerland)",
                            "de-DE": "German (Germany)",
                            "el": "Greek",
                            "el-GR": "Greek (Greece)",
                            "en": "English",
                            "en-AU": "English (Australia)",
                            "en-CA": "English (Canada)",
                            "en-GB": "English (Great Britain)",
                            "en-IN": "English (India)",
                            "en-NZ": "English (New Zealand)",
                            "en-SG": "English (Singapore)",
                            "en-US": "English (United States)",
                            "es": "Spanish",
                            "es-AR": "Spanish (Argentina)",
                            "es-ES": "Spanish (Spain)",
                            "es-UY": "Spanish (Uruguay)",
                            "et": "Estonian",
                            "et-EE": "Estonian (Estonia)",
                            "fi": "Finnish",
                            "fi-FI": "Finnish (Finland)",
                            "fr": "French",
                            "fr-BE": "French (Belgium)",
                            "fr-CA": "French (Canada)",
                            "fr-CH": "French (Switzerland)",
                            "fr-FR": "French (France)",
                            "fy": "Frisian",
                            "fy-NL": "Frisian (Netherlands)",
                            "hi": "Hindi",
                            "hr": "Croatian",
                            "hr-HR": "Croatian (Croatia)",
                            "is": "Icelandic",
                            "is-IS": "Icelandic (Iceland)",
                            "it": "Italian",
                            "it-CH": "Italian (Switzerland)",
                            "it-IT": "Italian (Italy)",
                            "ja": "Japanese",
                            "ko": "Korean",
                            "lt": "Lithuanian",
                            "lt-LT": "Lithuanian (Lithuania)",
                            "lv": "Latvian",
                            "lv-LV": "Latvian (Latvia)",
                            "nl": "Dutch",
                            "nl-BE": "Dutch (Belgium)",
                            "nl-NL": "Dutch (Netherlands)",
                            "no": "Norwegian",
                            "no-NO": "Norwegian (Norway)",
                            "pa": "Punjabi",
                            "pl": "Polish",
                            "pl-PL": "Polish (Poland)",
                            "pt": "Portuguese",
                            "pt-BR": "Portuguese (Brazil)",
                            "pt-PT": "Portuguese (Portugal)",
                            "ro": "Romanian",
                            "ro-RO": "Romanian (Romania)",
                            "ru": "Russian",
                            "ru-RU": "Russian (Russia)",
                            "sk": "Slovakian",
                            "sk-SK": "Slovakian (Slovakia)",
                            "sl": "Slovenian",
                            "sl-SI": "Slovenian (Slovenia)",
                            "sr": "Serbian",
                            "sr-RS": "Serbian (Serbia)",
                            "sv": "Swedish",
                            "sv-SE": "Swedish (Sweden)",
                            "te": "Telugu",
                            "zh": "Chinese",
                            "zh-CN": "Chinese (China)",
                            "zh-HK": "Chinese (Hong Kong)",
                            "zh-SG": "Chinese (Singapore)",
                            "zh-TW": "Chinese (Taiwan)",
                        },
                    )
                ),
                name="valid_language_choice",
            ),
        ),
    ]
