# Generated by Django 5.0.3 on 2024-03-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient_data", "0002_condition_claim_relatedcondition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="condition",
        ),
    ]
