RESOURCE_CONFIG = {
    "DocumentReference": {"fields": [{"title": "", "json_keys": []}]},
    "Claim": {"fields": [{"title": "", "json_keys": []}]},
    "MedicationRequest": {"fields": [{"title": "", "json_keys": []}]},
    "Condition": {"fields": [{"title": "", "json_keys": []}]},
    "Device": {"fields": [{"title": "", "json_keys": []}]},
    "ExplanationOfBenefit": {"fields": [{"title": "", "json_keys": []}]},
    "Immunization": {"fields": [{"title": "", "json_keys": []}]},
    "CarePlan": {"fields": [{"title": "", "json_keys": []}]},
    "CareTeam": {"fields": [{"title": "", "json_keys": []}]},
    "Provenance": {"fields": [{"title": "", "json_keys": []}]},
    "Procedure": {"fields": [{"title": "", "json_keys": []}]},
    "Encounter": {"fields": [{"title": "", "json_keys": []}]},
    "ImagingStudy": {"fields": [{"title": "", "json_keys": []}]},
    "Observation": {"fields": [{"title": "", "json_keys": []}]},
    "Medication": {"fields": [{"title": "", "json_keys": []}]},
    "MedicationAdministration": {"fields": [{"title": "", "json_keys": []}]},
    "DiagnosticReport": {"fields": [{"title": "", "json_keys": []}]},
    "AllergyIntolerance": {"fields": [{"title": "", "json_keys": []}]},
    "SupplyDelivery": {"fields": [{"title": "", "json_keys": []}]},
}
